let resList = [
  {
    id: "1",
    name: "KFC",
    cuisine: "South Asian",
    cloudinaryImageId: "qrqhfouxoeqt8aflj2yt",
    locality: "ITPL Main Road",
    areaName: "Whitefield",
    costForTwo: "₹300 for two",
    avgRating: 4.2,
  },
  {
    id: "2",
    name: "Meghana",
    cloudinaryImageId: "u3w6zgapfaun4zyt5pxn",
    locality: "ITPL Main Road",
    cuisine: "Chinese",
    areaName: "Whitefield",
    costForTwo: "₹300 for two",
    avgRating: 4.42,
  },
  {
    id: "3",
    name: "Hyderbad house",
    cloudinaryImageId: "qrqhfouxoeqt8aflj2yt",
    locality: "ITPL Main Road",
    areaName: "Whitefield",
    cuisine: "North Indian, Asian",
    costForTwo: "₹300 for two",
    avgRating: 4.62,
  },
  {
    id: "4",
    name: "trinetra",
    cloudinaryImageId: "thzhbierhb2qxhqsl0bo",
    locality: "ITPL Main Road",
    areaName: "Whitefield",
    costForTwo: "₹300 for two",
    uisine: "North Indian, Asian",
    avgRating: 3.2,
  },
  {
    id: "5",
    name: "KFC",
    cloudinaryImageId: "jwzxv4hmmnyuice4pe8x",
    locality: "ITPL Main Road",
    areaName: "Whitefield",
    costForTwo: "₹300 for two",
    uisine: "North Indian, Asian",
    avgRating: 4.2,
  },
  {
    id: "6",
    name: "KFC",
    cloudinaryImageId: "qrqhfouxoeqt8aflj2yt",
    locality: "ITPL Main Road",
    areaName: "Whitefield",
    costForTwo: "₹300 for two",
    avgRating: 4.2,
  },
];

export default resList;
